/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package marsrover;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @DisplayName("Given a single rover, when received commands, then the rover's position is updated.")
    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.CsvFileSource(resources = "/001WithInputsSingleRoverAndExpectedResults")
    void Test01(int startX, int startY, String startAngle, String commands,
                int endX, int endY,String endAngle) {

        int angleStart = Cardinal.valueOf(startAngle).getAngle();
        int angleEnds = Cardinal.valueOf(endAngle).getAngle();
        Rover rover1 =  new Rover(angleStart, startX, startY);

        for (int i = 0; i <commands.length() ; i++) {
            String currentCommand = String.valueOf(commands.charAt(i));
            var command = Commands.valueOf(currentCommand);
            command.applyToVehicule(rover1);
        }

        assertEquals(endX, rover1.getX());
        assertEquals(endY, rover1.getY());
        assertEquals(angleEnds,rover1.getAngle());

    }

    


}
