/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package marsrover;

public class App {
    public static void applyCommands(String commands) {
    }



    public static void main(String[] args) {
        System.out.println(new App());
    }
}
